import express from 'express';
import { submitJob, getSessionJobs, startNextJob, completeJob, getMyJob, requestEmergency, resolveEmergency, compareAlgorithms, exitQueue, fillDemo, clearDemo } from '../controllers/jobController.js';
import auth from '../middleware/auth.js';
const router = express.Router();
router.post('/submit', auth, submitJob);
router.get('/session/:id', auth, getSessionJobs);
router.patch('/session/:id/start-next', auth, startNextJob);
router.patch('/:jobId/complete', auth, completeJob);
router.get('/my', auth, getMyJob);
router.delete('/my', auth, exitQueue);
router.post('/emergency', auth, requestEmergency);
router.patch('/emergency/:emergencyId/resolve', auth, resolveEmergency);
router.get('/session/:id/compare', auth, compareAlgorithms);
router.post('/session/:id/demo', auth, fillDemo);
router.delete('/session/:id/demo', auth, clearDemo);
export default router;